--
-- Copyright 2008 Glencoe Software, Inc. All rights reserved.
-- Use is subject to license terms supplied in LICENSE.txt
--

-- This file was generated by dsl/resources/ome/dsl/views.vm
-- and can be used to overwrite the generated Map<Long, Long> tables
-- with functional views.

  DROP TABLE count_Dataset_projectLinks_7;

  CREATE OR REPLACE VIEW count_Dataset_projectLinks_7 (Dataset_id, owner_id, count) AS select child, owner_id, count(*)
    FROM projectdatasetlink GROUP BY child, owner_id ORDER BY child;

  DROP TABLE count_Dataset_imageLinks_by5;

  CREATE OR REPLACE VIEW count_Dataset_imageLinks_by5 (Dataset_id, owner_id, count) AS select parent, owner_id, count(*)
    FROM datasetimagelink GROUP BY parent, owner_id ORDER BY parent;

  DROP TABLE count_Dataset_annotationLin10;

  CREATE OR REPLACE VIEW count_Dataset_annotationLin10 (Dataset_id, owner_id, count) AS select parent, owner_id, count(*)
    FROM datasetannotationlink GROUP BY parent, owner_id ORDER BY parent;

  DROP TABLE count_Plate_screenLinks_by_4;

  CREATE OR REPLACE VIEW count_Plate_screenLinks_by_4 (Plate_id, owner_id, count) AS select child, owner_id, count(*)
    FROM screenplatelink GROUP BY child, owner_id ORDER BY child;

  DROP TABLE count_Plate_annotationLinks8;

  CREATE OR REPLACE VIEW count_Plate_annotationLinks8 (Plate_id, owner_id, count) AS select parent, owner_id, count(*)
    FROM plateannotationlink GROUP BY parent, owner_id ORDER BY parent;

  DROP TABLE count_Channel_annotationLin10;

  CREATE OR REPLACE VIEW count_Channel_annotationLin10 (Channel_id, owner_id, count) AS select parent, owner_id, count(*)
    FROM channelannotationlink GROUP BY parent, owner_id ORDER BY parent;

  DROP TABLE count_WellSample_annotation13;

  CREATE OR REPLACE VIEW count_WellSample_annotation13 (WellSample_id, owner_id, count) AS select parent, owner_id, count(*)
    FROM wellsampleannotationlink GROUP BY parent, owner_id ORDER BY parent;

  DROP TABLE count_PlaneInfo_annotationL12;

  CREATE OR REPLACE VIEW count_PlaneInfo_annotationL12 (PlaneInfo_id, owner_id, count) AS select parent, owner_id, count(*)
    FROM planeinfoannotationlink GROUP BY parent, owner_id ORDER BY parent;

  DROP TABLE count_Namespace_annotationL12;

  CREATE OR REPLACE VIEW count_Namespace_annotationL12 (Namespace_id, owner_id, count) AS select parent, owner_id, count(*)
    FROM namespaceannotationlink GROUP BY parent, owner_id ORDER BY parent;

  DROP TABLE count_Image_datasetLinks_by5;

  CREATE OR REPLACE VIEW count_Image_datasetLinks_by5 (Image_id, owner_id, count) AS select child, owner_id, count(*)
    FROM datasetimagelink GROUP BY child, owner_id ORDER BY child;

  DROP TABLE count_Image_annotationLinks8;

  CREATE OR REPLACE VIEW count_Image_annotationLinks8 (Image_id, owner_id, count) AS select parent, owner_id, count(*)
    FROM imageannotationlink GROUP BY parent, owner_id ORDER BY parent;

  DROP TABLE count_Project_datasetLinks_7;

  CREATE OR REPLACE VIEW count_Project_datasetLinks_7 (Project_id, owner_id, count) AS select parent, owner_id, count(*)
    FROM projectdatasetlink GROUP BY parent, owner_id ORDER BY parent;

  DROP TABLE count_Project_annotationLin10;

  CREATE OR REPLACE VIEW count_Project_annotationLin10 (Project_id, owner_id, count) AS select parent, owner_id, count(*)
    FROM projectannotationlink GROUP BY parent, owner_id ORDER BY parent;

  DROP TABLE count_Pixels_pixelsFileMaps8;

  CREATE OR REPLACE VIEW count_Pixels_pixelsFileMaps8 (Pixels_id, owner_id, count) AS select child, owner_id, count(*)
    FROM pixelsoriginalfilemap GROUP BY child, owner_id ORDER BY child;

  DROP TABLE count_Pixels_annotationLink9;

  CREATE OR REPLACE VIEW count_Pixels_annotationLink9 (Pixels_id, owner_id, count) AS select parent, owner_id, count(*)
    FROM pixelsannotationlink GROUP BY parent, owner_id ORDER BY parent;

  DROP TABLE count_LightPath_excitationF17;

  CREATE OR REPLACE VIEW count_LightPath_excitationF17 (LightPath_id, owner_id, count) AS select parent, owner_id, count(*)
    FROM lightpathexcitationfilterlink GROUP BY parent, owner_id ORDER BY parent;

  DROP TABLE count_LightPath_emissionFil15;

  CREATE OR REPLACE VIEW count_LightPath_emissionFil15 (LightPath_id, owner_id, count) AS select parent, owner_id, count(*)
    FROM lightpathemissionfilterlink GROUP BY parent, owner_id ORDER BY parent;

  DROP TABLE count_Roi_annotationLinks_b6;

  CREATE OR REPLACE VIEW count_Roi_annotationLinks_b6 (Roi_id, owner_id, count) AS select parent, owner_id, count(*)
    FROM roiannotationlink GROUP BY parent, owner_id ORDER BY parent;

  DROP TABLE count_Well_reagentLinks_by_4;

  CREATE OR REPLACE VIEW count_Well_reagentLinks_by_4 (Well_id, owner_id, count) AS select parent, owner_id, count(*)
    FROM wellreagentlink GROUP BY parent, owner_id ORDER BY parent;

  DROP TABLE count_Well_annotationLinks_7;

  CREATE OR REPLACE VIEW count_Well_annotationLinks_7 (Well_id, owner_id, count) AS select parent, owner_id, count(*)
    FROM wellannotationlink GROUP BY parent, owner_id ORDER BY parent;

  DROP TABLE count_Reagent_wellLinks_by_4;

  CREATE OR REPLACE VIEW count_Reagent_wellLinks_by_4 (Reagent_id, owner_id, count) AS select child, owner_id, count(*)
    FROM wellreagentlink GROUP BY child, owner_id ORDER BY child;

  DROP TABLE count_Reagent_annotationLin10;

  CREATE OR REPLACE VIEW count_Reagent_annotationLin10 (Reagent_id, owner_id, count) AS select parent, owner_id, count(*)
    FROM reagentannotationlink GROUP BY parent, owner_id ORDER BY parent;

  DROP TABLE count_OriginalFile_pixelsFi14;

  CREATE OR REPLACE VIEW count_OriginalFile_pixelsFi14 (OriginalFile_id, owner_id, count) AS select parent, owner_id, count(*)
    FROM pixelsoriginalfilemap GROUP BY parent, owner_id ORDER BY parent;

  DROP TABLE count_OriginalFile_annotati15;

  CREATE OR REPLACE VIEW count_OriginalFile_annotati15 (OriginalFile_id, owner_id, count) AS select parent, owner_id, count(*)
    FROM originalfileannotationlink GROUP BY parent, owner_id ORDER BY parent;

  DROP TABLE count_Annotation_annotation13;

  CREATE OR REPLACE VIEW count_Annotation_annotation13 (Annotation_id, owner_id, count) AS select parent, owner_id, count(*)
    FROM annotationannotationlink GROUP BY parent, owner_id ORDER BY parent;

  DROP TABLE count_Job_originalFileLinks8;

  CREATE OR REPLACE VIEW count_Job_originalFileLinks8 (Job_id, owner_id, count) AS select parent, owner_id, count(*)
    FROM joboriginalfilelink GROUP BY parent, owner_id ORDER BY parent;

  DROP TABLE count_FilterSet_excitationF17;

  CREATE OR REPLACE VIEW count_FilterSet_excitationF17 (FilterSet_id, owner_id, count) AS select parent, owner_id, count(*)
    FROM filtersetexcitationfilterlink GROUP BY parent, owner_id ORDER BY parent;

  DROP TABLE count_FilterSet_emissionFil15;

  CREATE OR REPLACE VIEW count_FilterSet_emissionFil15 (FilterSet_id, owner_id, count) AS select parent, owner_id, count(*)
    FROM filtersetemissionfilterlink GROUP BY parent, owner_id ORDER BY parent;

  DROP TABLE count_Screen_plateLinks_by_4;

  CREATE OR REPLACE VIEW count_Screen_plateLinks_by_4 (Screen_id, owner_id, count) AS select parent, owner_id, count(*)
    FROM screenplatelink GROUP BY parent, owner_id ORDER BY parent;

  DROP TABLE count_Screen_annotationLink9;

  CREATE OR REPLACE VIEW count_Screen_annotationLink9 (Screen_id, owner_id, count) AS select parent, owner_id, count(*)
    FROM screenannotationlink GROUP BY parent, owner_id ORDER BY parent;

  DROP TABLE count_PlateAcquisition_anno19;

  CREATE OR REPLACE VIEW count_PlateAcquisition_anno19 (PlateAcquisition_id, owner_id, count) AS select parent, owner_id, count(*)
    FROM plateacquisitionannotationlink GROUP BY parent, owner_id ORDER BY parent;

  DROP TABLE count_Filter_excitationFilt14;

  CREATE OR REPLACE VIEW count_Filter_excitationFilt14 (Filter_id, owner_id, count) AS select child, owner_id, count(*)
    FROM filtersetexcitationfilterlink GROUP BY child, owner_id ORDER BY child;

  DROP TABLE count_Filter_emissionFilter12;

  CREATE OR REPLACE VIEW count_Filter_emissionFilter12 (Filter_id, owner_id, count) AS select child, owner_id, count(*)
    FROM filtersetemissionfilterlink GROUP BY child, owner_id ORDER BY child;

